// <auto-generated />
namespace BrockAllen.MembershipReboot.Ef.Migrations.SqlAzure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5));
        
        string IMigrationMetadata.Id
        {
            get { return "201312211701328_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
