// <auto-generated />
namespace BrockAllen.MembershipReboot.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class VerificationState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VerificationState));
        
        string IMigrationMetadata.Id
        {
            get { return "201311230142548_VerificationState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
