// <auto-generated />
namespace BrockAllen.MembershipReboot.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v7_PhantomIndexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v7_PhantomIndexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201403261401393_v7_PhantomIndexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
