// <auto-generated />
namespace BrockAllen.MembershipReboot.Migrations.SqlServer
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class VerificationPurpose : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VerificationPurpose));
        
        string IMigrationMetadata.Id
        {
            get { return "201304160322055_VerificationPurpose"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
