// <auto-generated />
namespace BrockAllen.MembershipReboot.Migrations.SqlServer
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ExpandKeyAndAddAccountCloseFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpandKeyAndAddAccountCloseFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201302251410424_ExpandKeyAndAddAccountCloseFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
